
[ServerConfig]
server_name = "FastAPIServer"
port = 9300
code_generate_before_run = false

[LogConfig]
print_console = true
print_file = true
print_stack = true
print_color = true
trace_stack_size = 10
log_level = "debug"

[ContentsDBConfig]
db_type = "mysql"
host = "localhost"
port = 3306
name = "dbname"
id = ""
pw = ""
show_log = false

[LogDBConfig]
db_type = "mongodb"
host = "localhost"
port = 27017
name = "dbname"
id = ""
pw = ""
show_log = true

[JwtToken]
access_key = "temp_access"
refresh_key = "temp_refresh"
access_expire_min = 30
refresh_expire_day = 7