
[ServerConfig]
server_name = "FastAPIServer"
port = 9000
code_generate_before_run = false
is_chat = false

[LogConfig]
print_console = true
print_file = true
print_stack = true
print_color = true
trace_stack_size = 10
log_level = "debug"

[ContentsDBConfig]
db_type = "mysql"
host = "localhost"
port = 3306
name = "db_name"
id = "admin_id"
pw = "pw"
show_log = false

[RedisConfig]
db_type = "redis"
host = ""
port = 6379
pw = ""
show_log = true

[MongoDBConfig]
db_type = "mongodb"
host = "localhost"
port = 27017
name = ""
id = ""
pw = ""
show_log = true

[JwtToken]
access_key = "access_key"
refresh_key = "refresh_key"
access_expire_min = 30
refresh_expire_day = 7