
######################################################################
#                                                                    #
# This file is automatically generated, DO NOT modify it arbitrarily #
#                                                                    #
######################################################################

from common.gmodel import StructModel
            
class DataScript(StructModel):    
    def __init__(self) -> None:
        super().__init__()
                            
    def GetKeyCol(self) -> str:
        return ""
    
    def GetArrayCols(self) -> set[str]:
        return {}


class TestExcelData(DataScript):
    
    Id:int = 0
    Name:list[str] = list()
    Number:list[int] = list()
    
    def __init__(self, Id, Name, Number) -> None:
        super().__init__()
        
        self.Id = Id
        self.Name = Name
        self.Number = Number
                        
    def GetKeyCol(self) -> str:
        return "Id"
    
    def GetArrayCols(self) -> set[str]:
        return {"Name", "Number"}



class TestSecondData(DataScript):
    
    Id:int = 0
    Seconds:list[str] = list()
    IsString:bool = False
    Number:list[int] = list()
    
    def __init__(self, Id, Seconds, IsString, Number) -> None:
        super().__init__()
        
        self.Id = Id
        self.Seconds = Seconds
        self.IsString = IsString
        self.Number = Number
                        
    def GetKeyCol(self) -> str:
        return "Id"
    
    def GetArrayCols(self) -> set[str]:
        return {"Seconds", "Number"}



def GetDataList() -> list[DataScript]:
    return [
        TestExcelData(1, ["Hi"], [15]),
        TestExcelData(2, ["My"], [1]),
        TestExcelData(3, ["lol"], [10]),
        TestExcelData(3, ["lol2"], [250]),
        TestExcelData(3, ["wow"], [13]),
        TestSecondData(1, ["Hi"], True, [15]),
        TestSecondData(2, ["My"], True, [1]),
        TestSecondData(3, ["lol"], True, [10]),
        TestSecondData(3, ["lol2"], True, [250]),
        TestSecondData(3, ["wow"], True, [13])
        ]
            
